/**
 * Renderer-side update badge, injected into the dsh web GUI.
 *
 * The web frontend belongs to the upstream harness repo; rather than fork its
 * UI, the shell injects a self-contained overlay pinned to the bottom-left of
 * the window — visually the sidebar's lower corner. The injected script
 * defines one global, __dshDesktopApplyUpdateState(state), which the main
 * process drives over IPC (bridged by preload as window.dshDesktop) on every
 * update-state change. A MutationObserver re-mounts the overlay if the SPA
 * wipes the body, and each injection is idempotent.
 */

/** Overlay styles: dark theme pill pinned to the window's bottom-left. */
export const BADGE_CSS = [
  '#dsh-update-badge{position:fixed;left:12px;bottom:12px;z-index:2147483000;',
  'font-family:"Segoe UI",system-ui,sans-serif;font-size:12px;color:#c9d4e3;',
  'pointer-events:none}',
  '#dsh-update-badge *{box-sizing:border-box}',
  '.dsh-upd-pill{pointer-events:auto;display:inline-flex;align-items:center;gap:6px;',
  'padding:6px 12px;border-radius:999px;background:#161d29;border:1px solid #2a3a55;',
  'color:#d7e2f2;cursor:pointer;user-select:none;box-shadow:0 4px 16px rgba(0,0,0,.45)}',
  '.dsh-upd-available{border-color:#3b82f6;color:#bfdbfe;background:#12233f}',
  '.dsh-upd-downloading{border-color:#22304a;color:#9fb3cc}',
  '.dsh-upd-downloaded{border-color:#22c55e;color:#bbf7d0;background:#10241a}',
  '.dsh-upd-card{pointer-events:auto;margin-top:8px;width:264px;padding:12px;',
  'background:#10141c;border:1px solid #26334c;border-radius:10px;',
  'box-shadow:0 8px 28px rgba(0,0,0,.55)}',
  '.dsh-upd-title{font-weight:600;font-size:12.5px;margin-bottom:6px;color:#e6edf7}',
  '.dsh-upd-item{margin:3px 0;color:#aab8cc;line-height:1.45}',
  '.dsh-upd-error{margin:6px 0 0;color:#f87171;font-size:11.5px}',
  '.dsh-upd-bar{height:5px;border-radius:3px;background:#1c2740;margin-top:8px;overflow:hidden}',
  '.dsh-upd-bar-in{height:100%;background:#3b82f6;border-radius:3px;transition:width .25s}',
  '.dsh-upd-prog{margin-top:5px;font-size:11px;color:#8fa1ba}',
  '.dsh-upd-actions{display:flex;flex-wrap:wrap;gap:8px;margin-top:10px}',
  '.dsh-upd-btn{flex:1 1 auto;padding:5px 10px;border-radius:6px;border:1px solid #2a3a55;',
  'background:#182236;color:#d7e2f2;font-size:12px;cursor:pointer;font-family:inherit}',
  '.dsh-upd-btn:hover{background:#1f2c46}',
  '.dsh-upd-primary{background:#2563eb;border-color:#2563eb;color:#fff}',
  '.dsh-upd-primary:hover{background:#1d4fd8}',
  '.dsh-upd-foot{margin-top:9px;font-size:11px;color:#5f7089;cursor:pointer;text-align:right}',
  '.dsh-upd-foot:hover{color:#8fa1ba;text-decoration:underline}',
].join('')

/**
 * The once-per-page bootstrap defining window.__dshDesktopApplyUpdateState.
 * Written in ES5-flavored JS because it executes verbatim in the page world;
 * the CSS payload is spliced in as a JSON literal.
 */
export const BADGE_BOOTSTRAP = [
  '(function () {',
  '  if (window.__dshDesktopApplyUpdateState) { return; }',
  '  var state = null;',
  '  var dismissedAt = 0;',
  '  var cardOpen = false;',
  '  var bridge = window.dshDesktop || null;',
  '',
  '  function pct(s) {',
  '    if (!s.totalBytes) { return 0; }',
  '    return Math.min(100, Math.round((s.receivedBytes / s.totalBytes) * 100));',
  '  }',
  '  function mb(n) { return (n / 1048576).toFixed(1); }',
  '',
  '  function mount() {',
  '    var host = document.getElementById("dsh-update-badge");',
  '    if (host) { return host; }',
  '    var root = document.body || document.documentElement;',
  '    host = document.createElement("div");',
  '    host.id = "dsh-update-badge";',
  '    root.appendChild(host);',
  '    return host;',
  '  }',
  '',
  '  function hideBadge() {',
  '    var stale = document.getElementById("dsh-update-badge");',
  '    if (stale && stale.parentNode) { stale.parentNode.removeChild(stale); }',
  '  }',
  '',
  '  function render() {',
  '    var visible = state && (state.status === "available" || state.status === "downloading" || state.status === "downloaded");',
  '    if (!visible || (dismissedAt && state.status === "available" && state.checkedAt && state.checkedAt <= dismissedAt)) {',
  '      hideBadge();',
  '      return;',
  '    }',
  '    var host = mount();',
  '    while (host.firstChild) { host.removeChild(host.firstChild); }',
  '',
  '    var pill = document.createElement("div");',
  '    pill.className = "dsh-upd-pill dsh-upd-" + state.status;',
  '    pill.setAttribute("role", "button");',
  '    var label;',
  '    if (state.status === "downloading") {',
  '      label = "\u2b07 \u4e0b\u8f7d\u4e2d " + pct(state) + "%";',
  '    } else if (state.status === "downloaded") {',
  '      label = "\u2713 \u66f4\u65b0\u5df2\u4e0b\u8f7d";',
  '    } else {',
  '      label = "\u2b06 \u53d1\u73b0\u66f4\u65b0";',
  '    }',
  '    pill.textContent = label;',
  '    pill.addEventListener("click", function (event) {',
  '      event.stopPropagation();',
  '      cardOpen = !cardOpen;',
  '      render();',
  '    });',
  '    host.appendChild(pill);',
  '',
  '    if (!cardOpen) { return; }',
  '    var card = document.createElement("div");',
  '    card.className = "dsh-upd-card";',
  '    card.addEventListener("click", function (event) { event.stopPropagation(); });',
  '',
  '    var title = document.createElement("div");',
  '    title.className = "dsh-upd-title";',
  '    title.textContent = "\u53ef\u7528\u66f4\u65b0";',
  '    card.appendChild(title);',
  '',
  '    var items = state.items || [];',
  '    for (var i = 0; i < items.length; i++) {',
  '      var item = items[i];',
  '      var row = document.createElement("div");',
  '      row.className = "dsh-upd-item";',
  '      row.textContent = (item.kind === "desktop"',
  '        ? "\u684c\u9762\u7248 " + item.current + " \u2192 " + item.latest',
  '        : "\u5185\u7f6e dsh " + item.current + " \u2192 " + item.latest);',
  '      card.appendChild(row);',
  '    }',
  '    if (items.length === 0) {',
  '      var note = document.createElement("div");',
  '      note.className = "dsh-upd-item";',
  '      note.textContent = (state.status === "downloaded"',
  '        ? "\u5b89\u88c5\u5305\u5df2\u5c31\u7eea"',
  '        : "\u6b63\u5728\u4e0b\u8f7d\u66f4\u65b0\u5b89\u88c5\u5305\u2026");',
  '      card.appendChild(note);',
  '    }',
  '',
  '    if (state.errorNote) {',
  '      var err = document.createElement("div");',
  '      err.className = "dsh-upd-error";',
  '      err.textContent = state.errorNote;',
  '      card.appendChild(err);',
  '    }',
  '',
  '    if (state.status === "downloading") {',
  '      var barOuter = document.createElement("div");',
  '      barOuter.className = "dsh-upd-bar";',
  '      var barInner = document.createElement("div");',
  '      barInner.className = "dsh-upd-bar-in";',
  '      barInner.style.width = pct(state) + "%";',
  '      barOuter.appendChild(barInner);',
  '      card.appendChild(barOuter);',
  '      var prog = document.createElement("div");',
  '      prog.className = "dsh-upd-prog";',
  '      prog.textContent = mb(state.receivedBytes || 0) + " / " + (state.totalBytes ? mb(state.totalBytes) + " MB" : "\u2026");',
  '      card.appendChild(prog);',
  '    }',
  '',
  '    var actions = document.createElement("div");',
  '    actions.className = "dsh-upd-actions";',
  '    function button(text, primary, handler) {',
  '      var b = document.createElement("button");',
  '      b.className = "dsh-upd-btn" + (primary ? " dsh-upd-primary" : "");',
  '      b.textContent = text;',
  '      b.addEventListener("click", handler);',
  '      actions.appendChild(b);',
  '    }',
  '    if (state.status === "available") {',
  '      if (bridge && bridge.startDownload) {',
  '        button("\u4e0b\u8f7d\u5b89\u88c5\u5305", true, function () { bridge.startDownload(); });',
  '      }',
  '      if (bridge && bridge.openReleases && state.releaseUrl) {',
  '        button("\u53d1\u5e03\u9875", false, function () { bridge.openReleases(); });',
  '      }',
  '    } else if (state.status === "downloaded") {',
  '      if (bridge && bridge.openFile) {',
  '        button("\u6253\u5f00\u6240\u5728\u6587\u4ef6\u5939", false, function () { bridge.openFile(); });',
  '      }',
  '      if (bridge && bridge.installNow) {',
  '        button("\u7acb\u5373\u5b89\u88c5", true, function () { bridge.installNow(); });',
  '      }',
  '    } else if (state.status === "downloading") {',
  '      button("\u9690\u85cf", false, function () { cardOpen = false; render(); });',
  '    }',
  '    card.appendChild(actions);',
  '',
  '    var foot = document.createElement("div");',
  '    foot.className = "dsh-upd-foot";',
  '    foot.textContent = "\u7a0d\u540e\u518d\u63d0\u9192";',
  '    foot.addEventListener("click", function () {',
  '      dismissedAt = (state && state.checkedAt) ? state.checkedAt : Date.now();',
  '      cardOpen = false;',
  '      render();',
  '    });',
  '    card.appendChild(foot);',
  '    host.appendChild(card);',
  '  }',
  '',
  '  var style = document.createElement("style");',
  '  style.id = "dsh-update-badge-style";',
  '  style.textContent = "__BADGE_CSS__";',
  '  (document.head || document.documentElement).appendChild(style);',
  '',
  '  window.__dshDesktopApplyUpdateState = function (next) {',
  '    state = next;',
  '    if (state && state.status !== "available") { dismissedAt = 0; }',
  '    render();',
  '  };',
  '',
  '  document.addEventListener("click", function () {',
  '    if (cardOpen) { cardOpen = false; render(); }',
  '  });',
  '',
  '  if (typeof MutationObserver !== "undefined") {',
  '    new MutationObserver(function () {',
  '      if ((state && state.status !== "up-to-date" && state.status !== "idle") && !document.getElementById("dsh-update-badge")) { render(); }',
  '    }).observe(document.documentElement, { childList: true, subtree: true });',
  '  }',
  '',
  '  if (bridge) {',
  '    if (bridge.onStateChanged) { bridge.onStateChanged(function (s) { window.__dshDesktopApplyUpdateState(s); }); }',
  '    if (bridge.getState) { bridge.getState().then(function (s) { window.__dshDesktopApplyUpdateState(s); }); }',
  '  }',
  '})();',
].join('\n').replace('"__BADGE_CSS__"', JSON.stringify(BADGE_CSS))

/** Build one executeJavaScript payload applying a concrete state. */
export function applyBadgeStateJs(state: unknown): string {
  return 'window.__dshDesktopApplyUpdateState && window.__dshDesktopApplyUpdateState(' + JSON.stringify(state) + ')'
}
